description: >
  Sample description

executor: default

parameters:
  config-list-path:
    type: string
    default: /tmp/config-list
    description: >
      A file path to append config paths.
      Each path in this file should be relateive to the working directory.
  fixed-config-paths:
    type: string
    default: ""
    description: >
      Multiline string of fixed config paths to append. One path for each line.
      Each path should be relateive to the working directory.
  find-config-regex:
    type: string
    default: ""
    description: >
      Regex to find configs from the working directory.
  generated-config-path:
    type: string
    default: /tmp/generated-config.yml
    description: >
      A file path for the generated config file.

steps:
  - checkout
  - when:
      condition: << parameters.fixed-config-paths >>
      steps:
        - append-fixed-paths:
            config-list-path: << parameters.config-list-path >>
            fixed-config-paths: << parameters.fixed-config-paths >>
  - when:
      condition: << parameters.find-config-regex >>
      steps:
        - append-find-result:
            config-list-path: << parameters.config-list-path >>
            find-config-regex: << parameters.find-config-regex >>
  - generate-config:
      config-list-path: << parameters.config-list-path >>
      generated-config-path: << parameters.generated-config-path >>
