description: >
  cimg/go image with CUE
docker:
  - image: bufferings/cimg-cue:<<parameters.tag>>
parameters:
  tag:
    type: string
    default: latest
    description: >
      Pick a specific bufferings/cimg-cue image variant:
      https://hub.docker.com/r/bufferings/cimg-cue/tags
