description: >
  You can use regex to specify the split configs.

  Please check README in the GitHub repository for more details:
  https://github.com/bufferings/orb-split-config

usage:
  version: 2.1
  setup: true
  orbs:
    # Please specify the latest version
    split-config: bufferings/split-config@1.2.3
  workflows:
    generate-config:
      jobs:
        - split-config/generate-config:
            find-config-regex: .*/\.circleci/config\.yml
